// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5avLDgWUIoASA2sKv3R5qgVc42B0j43c',
    appId: '1:869159116338:web:d1f56aefd8a1e59027a62b',
    messagingSenderId: '869159116338',
    projectId: 'flutterauthdemo-ad0e8',
    authDomain: 'flutterauthdemo-ad0e8.firebaseapp.com',
    storageBucket: 'flutterauthdemo-ad0e8.firebasestorage.app',
    measurementId: 'G-XP4FRBV3GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0B-fuQM1Ukoa9sUhi09upNacEhAF3aCc',
    appId: '1:869159116338:android:dea526d3bd6cea5d27a62b',
    messagingSenderId: '869159116338',
    projectId: 'flutterauthdemo-ad0e8',
    storageBucket: 'flutterauthdemo-ad0e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsa9NWWS90-rTXseStAk7VQA6DU_BS7vU',
    appId: '1:869159116338:ios:da2e2b7d830e3db127a62b',
    messagingSenderId: '869159116338',
    projectId: 'flutterauthdemo-ad0e8',
    storageBucket: 'flutterauthdemo-ad0e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsa9NWWS90-rTXseStAk7VQA6DU_BS7vU',
    appId: '1:869159116338:ios:da2e2b7d830e3db127a62b',
    messagingSenderId: '869159116338',
    projectId: 'flutterauthdemo-ad0e8',
    storageBucket: 'flutterauthdemo-ad0e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5avLDgWUIoASA2sKv3R5qgVc42B0j43c',
    appId: '1:869159116338:web:ad875c58f3b03e1827a62b',
    messagingSenderId: '869159116338',
    projectId: 'flutterauthdemo-ad0e8',
    authDomain: 'flutterauthdemo-ad0e8.firebaseapp.com',
    storageBucket: 'flutterauthdemo-ad0e8.firebasestorage.app',
    measurementId: 'G-9XGHBVZPKL',
  );
}
